Implemented validation for simple letters count
ArefMozafari/flutter_pw_validator pull request #15
Opened 2022-01-28 12:44 UTC by jeffersonmello

I needed a simple validation of the number of letters the component did not have this functionality.

I implemented it if you think it's interesting to keep in the project follow the PR.

2022-01-31 09:28 UTC, ArefMozafari commented
Can't you pass all values 0 and use the minLength property to suit your needs?

2022-01-31 11:24 UTC, jeffersonmello commented
> Can't you pass all values 0 and use the minLength property to suit your needs?

I my case no, i need validation for min 3 numbers, min 1 upper case letter and min 3 letters.

2022-01-31 11:50 UTC, ArefMozafari requested changes

2022-01-31 11:50 UTC, ArefMozafari commented on lib/Utilities/Validator.dart
> +  bool hasMinNormalChar(String password, int normalCount) {
It would be great if you could include a test for this in `Validator_test.dart`

2022-02-26 12:59 UTC, jeffersonmello commented
@ArefMozafari tests already implemented

2022-02-28 12:58 UTC, ArefMozafari commented
Thanks
I will merge this

2022-03-01 07:11 UTC, merged